apiVersion: apps/v1
kind: Deployment
metadata:
  name: evolution
spec:
  template:
    spec:
      volumes:
        - name: evolution-claim0
          persistentVolumeClaim:
            claimName: dev-evolution-claim0