apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev

resources:
  - ../../k8s

configMapGenerator:
  - name: postgres-config
    behavior: merge
    literals:
      - POSTGRES_HOST_AUTH_METHOD=trust

secretGenerator:
  - name: evolution-secret
    behavior: merge
    literals:
      - CACHE_REDIS_URI=redis://dev-redis:6379/6
      - AUTHENTICATION_API_KEY=teste
      - DATABASE_CONNECTION_URI=postgresql://user:pass@dev-postgres:5432/dev-evolution?schema=public
      - DATABASE_URL=postgresql://user:pass@dev-postgres:5432/dev-evolution?schema=public
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_exchange
  
  - name: n8n-secret
    behavior: create
    literals:
      - DB_POSTGRESDB_DATABASE=dev-n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_PASSWORD=pass
      - DB_POSTGRESDB_USER=user
      - DB_POSTGRESDB_HOST=dev-postgres

patches:
  - path: n8n-replicas-patch.yaml
    target:
      kind: Deployment
      name: n8n
      
  - path: evolution-pvc-patch.yaml
    target:
      kind: Deployment
      name: evolution