services:
  evolution:
    container_name: evolution
    image: atendai/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    volumes:
      - ./data/evolution:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 8080
      
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - evolution-net
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=evolution
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    expose:
      - 5432
      
  n8n:
    container_name: n8n
    image: n8nio/n8n:latest
    restart: always
    ports:
      - 5678:5678
    volumes:
      - ./data/n8n:/home/node/.n8n
    networks:
      - evolution-net
    environment:
      - N8N_PROTOCOL=http
      - N8N_HOST=0.0.0.0
      - N8N_EDITOR_BASE_URL=http://192.168.15.6:5678
      - WEBHOOK_URL=http://n8n:5678/
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=evolution
      - DB_POSTGRESDB_USER=user
      - DB_POSTGRESDB_PASSWORD=pass

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
