apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
- namespace.yaml
- configmaps/postgres-configmap.yaml
- secrets/postgres-secret.yaml

- deployments/postgres-deployment.yaml
- deployments/redis-deployment.yaml
- deployments/nginx-deployment.yaml

- services/postgres-service.yaml
- services/redis-service.yaml
- services/nginx-service.yaml
- services/ingress-nginx-lb-service.yaml

- ingress/nginx-ingress.yaml
