apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  labels:
    app: n8n
    domain: automacao
type: Opaque
stringData:
  DB_POSTGRESDB_DATABASE: dev-n8n
  DB_POSTGRESDB_PORT: '5432'
  DB_POSTGRESDB_USER: user
  DB_POSTGRESDB_PASSWORD: pass
  DB_POSTGRESDB_HOST: postgres.shared.svc.cluster.local
  # overlays/dev/secrets/n8n-secret.yaml

  #- DB_POSTGRESDB_PORT=5432