apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evolution-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: evolution.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evolution
                port:
                  number: 8080