apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          volumeMounts:
            - name: dev-postgres-pvc
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: dev-postgres-pvc
          persistentVolumeClaim:
            claimName: dev-postgres-pvc