apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
        - name: redis
          volumeMounts:
            - name: redis-claim0
              mountPath: /data
      volumes:
        - name: redis-claim0
          persistentVolumeClaim:
            claimName: dev-redis-claim0