apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
        - name: redis
          volumeMounts:
            - name: dev-redis-pvc
              mountPath: /data
      volumes:
        - name: dev-redis-pvc
          persistentVolumeClaim:
            claimName: redis-pvc