apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-
namespace: staging

resources:
  - ../../k8s

patches:
  - path: n8n-replicas-patch.yaml
    target:
      kind: Deployment
      name: n8n