apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  template:
    spec:
      initContainers:
        - name: create-prod-n8n-db
          image: postgres:15
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: DB_POSTGRESDB_PASSWORD
          command:
            - sh
            - -c
            - |
              until psql -h postgres.shared.svc.cluster.local -U "$DB_POSTGRESDB_USER" -tc "SELECT 1 FROM pg_database WHERE datname = 'prod-n8n'" | grep -q 1; do
                echo "Creating prod-n8n DB..."; 
                psql -h postgres.shared.svc.cluster.local -U "$DB_POSTGRESDB_USER" -c "CREATE DATABASE \"prod-n8n\"";
                sleep 2;
              done
          envFrom:
            - secretRef:
                name: n8n-secret