apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        app: redis
    spec:
      restartPolicy: Always
      containers:
        - args:
            - redis-server
            - --port
            - "6379"
            - --appendonly
            - "yes"
          image: redis:latest
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
          # volumeMounts:
          #   - mountPath: /data
          #     name: redis-claim0

      # volumes:
      #   - name: redis-claim0
      #     persistentVolumeClaim:
      #       claimName: redis-claim0
