apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmaps/postgres-configmap.yaml
- configmaps/n8n-configmap.yaml
- configmaps/evolution-configmap.yaml

- deployments/postgres-deployment.yaml
- deployments/redis-deployment.yaml
- deployments/n8n-deployment.yaml
- deployments/evolution-deployment.yaml
- deployments/nginx-deployment.yaml

- services/postgres-service.yaml
- services/redis-service.yaml
- services/n8n-service.yaml
- services/evolution-service.yaml
- services/nginx-service.yaml
- services/ingress-nginx-lb-service.yaml

- ingress/n8n-ingress.yaml
- ingress/evolution-ingress.yaml
- ingress/nginx-ingress.yaml
