apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: prod

resources:
  - ../../k8s

patches:
  - path: n8n-replicas-patch.yaml
    target:
      kind: Deployment
      name: n8n
  - path: evolution-pvc-patch.yaml
    target:
      kind: Deployment
      name: evolution