apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evolution-pvc
  labels:
    app: evolution
    domain: automacao
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


      