apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmaps/n8n-configmap.yaml
  - configmaps/evolution-configmap.yaml

  - deployments/n8n-deployment.yaml
  - deployments/evolution-deployment.yaml

  - services/n8n-service.yaml
  - services/evolution-service.yaml

  - ingress/n8n-ingress.yaml
  - ingress/evolution-ingress.yaml
