apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    app: n8n
  name: n8n
spec:
  selector:
    matchLabels:
      app: n8n
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        app: n8n
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z dev-postgres 5432; do echo waiting for postgres; sleep 2; done;']

        - name: create-dev-n8n-db
          image: postgres:15
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: DB_POSTGRESDB_PASSWORD
          command:
            - sh
            - -c
            - |
              until psql -h dev-postgres -U $DB_POSTGRESDB_USER -tc "SELECT 1 FROM pg_database WHERE datname = 'dev-n8n'" | grep -q 1; do
                echo "Creating dev-n8n DB..."; 
                psql -h dev-postgres -U $DB_POSTGRESDB_USER -c "CREATE DATABASE \"dev-n8n\"";
                sleep 2;
              done
          envFrom:
            - secretRef:
                name: n8n-secret

      containers:
        - name: n8n
          image: n8nio/n8n:latest
          envFrom:
            - configMapRef:
                name: n8n-config
            - secretRef:
                name: n8n-secret
          ports:
            - containerPort: 5678
              protocol: TCP
      restartPolicy: Always