apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  labels:
    app: n8n
    domain: automacao
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


      