apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  template:
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /home/node/.n8n"]
          volumeMounts:
            - name: dev-n8n-pvc
              mountPath: /home/node/.n8n
      containers:
        - name: n8n
          volumeMounts:
            - name: dev-n8n-pvc
              mountPath: /home/node/.n8n
      volumes:
        - name: dev-n8n-pvc
          persistentVolumeClaim:
            claimName: n8n-pvc