# patches/evolution-pvc-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evolution
spec:
  template:
    spec:
      containers:
        - name: evolution
          volumeMounts:
            - name: evolution-claim0
              mountPath: /evolution/instances
      volumes:
        - name: evolution-claim0
          persistentVolumeClaim:
            claimName: prod-evolution-claim0