apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          volumeMounts:
            - name: postgres-claim0
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-claim0
          persistentVolumeClaim:
            claimName: prod-postgres-claim0