apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-basic

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - ingressclass.yaml